### POST
POST http://localhost:9000/service/Zoo/Greet
apikey: 8DDBD07E-3F23-48E3-B220-8F78C6E7F8DC

["Larziboy"]

### Hello, authorization
POST http://localhost:9000/service/OCoreAuthorizationService/Hello

